---
- name: Attempting to execute os family specific tasks (Debian)
  tags: dhclient
  include_tasks: "dhclient_{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == 'Debian'

- name: Attempting to execute os family specific tasks (RedHat)
  tags: dhclient
  include_tasks: "dhclient_{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Ensure that the dhclient package is installed
  tags: dhclient
  become: true
  package:
    name: "{{ dhclient_pkg }}"
    state: present
  register: dhclient_package

- name: Attempting to overlay dhcp configurations
  tags: dhclient
  become: true
  template:
    src: dhclient.conf.j2
    dest: "{{ dhclient_cfg }}/dhclient-{{ item.interface }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart dhcp
  with_items: "{{ dhclient }}"
  when:
    - dhclient|length > 0
    - dhclient_package is success
    - item.interface is defined
    - item.settings|length > 0

- name: Ensure that dhcp is started and enabled on boot
  tags: dhclient
  become: true
  service:
    enabled: yes
    name: "{{ dhclient_svc }}"
    state: started
  when: dhclient_package is success
...
